name: C/C++ CI

on: 
  [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
#     - name: configure
#       run: ./configure
#     - name: make
#       run: make
#     - name: make check
#       run: make check
#     - name: make distcheck
#       run: make distcheck
    - name: Build c++ project
      uses: nicledomaS/cmake_build_action@v1
      with:
        submodule_update: ON
        run_tests: OFF
        unit_test_build: -Dtest=OFF
